// Canonical titles for each stat
export const STAT_TITLES = {
  mean: 'Mean',
  meanMin: 'Mean min',
  meanMax: 'Mean max',
  median: 'Median',
  min: 'Min',
  max: 'Max',
  diff: 'Diff',
  stdev: 'Stdev',
  rstdev: 'Rstdev',
  moe: 'Moe',
  rmoe: 'Rmoe',
  outliersMin: 'Outliers min',
  outliersMax: 'Outliers max',
  times: 'Times',
  loops: 'Loops',
  repeat: 'Repeat',
  samples: 'Samples',
  minLoopDuration: 'Min loop',
  histogram: 'Histogram',
  quantiles: 'Quantiles',
}
